### ISSUE TITLE
T class template plural method string isn't extracted bt xgettext

### ISSUE THREAD

**Issue by jeusdi** [neris/NGettext#7]
I'm using your `T` class in order to mark my strings.

I perform this `xgettext` command:

```
xgettext -kT._ -kT._n -LC# --omit-header --from-code=UTF-8 -o messages.pot -c -n ./TransClassOne.cs
```

In my dummy class I have strings like these:

```
public string sayHello(string person, int n)
{
    return String.Format(Utils.T._n("Hello, {0} - once!!", "Hello, {0} - twice or more!!", n), person);
}
```

After perform `xgettext` command, it only extracts first parameter string value: `"Hello, {0} - once"`.

I've tried specifying `-kT._ -kT._n`.
Any idea?

**Comment by neris** [comment]
First of all, I recommend to use [Poedit](http://poedit.net/) to extract messages from code (and translate messages too). You can read how to use it at the bottom of NGettext's readme file.

If you like to use `xgettext`, instead of your `-k` options you need to specify keyword list like this:
```
--keyword="_;_n:1,2;_p:1c,2;_pn:1c,2,3"
``` 
for the `T` class interface and/or 
```
--keyword="GetString;GetPluralString:1,2;GetParticularString:1c,2;GetParticularPluralString:1c,2,3"
```
for original `ICatalog` interface. But I'm not sure about this syntax, maybe you do need to separate keywords with `-k` option.

**Comment by neris** [comment]
I think correct syntax is like this:
```
xgettext -k_ -k_n:1,2 -k_p:1c,2 -k_pn:1c,2,3
```
and
```
xgettext -kGetString -kGetPluralString:1,2 -kGetParticularString:1c,2 -kGetParticularPluralString:1c,2,3
```
